"""add_bulk_prices_to_products

Revision ID: 38cbcb8cd12d
Revises: cf2c93889c9c
Create Date: 2025-05-03 13:49:11.338077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38cbcb8cd12d'
down_revision: Union[str, None] = 'cf2c93889c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('bulk_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'bulk_prices')
    # ### end Alembic commands ###
