"""add_product_dimensions_weight_material

Revision ID: a52c2e429920
Revises: 6dd62ae35721
Create Date: 2025-05-03 18:21:23.822325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a52c2e429920'
down_revision: Union[str, None] = '6dd62ae35721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('material', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'material')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'dimensions')
    # ### end Alembic commands ###
