"""Add order counter

Revision ID: af27ca418445
Revises: bceebd08c8ec
Create Date: 2025-03-17 22:37:28.347706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af27ca418445'
down_revision: Union[str, None] = 'bceebd08c8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.add_column('orders', sa.Column('clerkId', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('receipt_id', sa.Integer(), nullable=True))
    op.drop_index('ix_orders_clerk_id', table_name='orders')
    op.create_index(op.f('ix_orders_clerkId'), 'orders', ['clerkId'], unique=False)
    op.create_foreign_key(None, 'orders', 'receipts', ['receipt_id'], ['id'], ondelete='SET NULL')
    op.drop_column('orders', 'clerk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('clerk_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_clerkId'), table_name='orders')
    op.create_index('ix_orders_clerk_id', 'orders', ['clerk_id'], unique=False)
    op.drop_column('orders', 'receipt_id')
    op.drop_column('orders', 'clerkId')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###
