"""Add user_customization_options to categories

Revision ID: bb0ce49579a8
Revises: f233c6726fb2
Create Date: 2025-03-17 20:49:15.970672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb0ce49579a8'
down_revision: Union[str, None] = 'f233c6726fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('categories', sa.Column(
        'user_customization_options',
        postgresql.JSONB(astext_type=sa.Text()),  # ✅ Proper way
        nullable=True
    ))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'user_customization_options')
    # ### end Alembic commands ###
