"""Add order counter

Revision ID: bceebd08c8ec
Revises: 4a6e83fc0e3c
Create Date: 2025-03-17 22:12:57.216011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bceebd08c8ec'
down_revision: Union[str, None] = '4a6e83fc0e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_counter_id'), 'order_counter', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_counter_id'), table_name='order_counter')
    op.drop_table('order_counter')
    # ### end Alembic commands ###
