"""update_bulk_prices_to_use_ranges

Revision ID: bcfbf184f89a
Revises: ac1e623f7f32
Create Date: 2025-05-04 01:48:59.378494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcfbf184f89a'
down_revision: Union[str, None] = 'ac1e623f7f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
