"""added models for all featured sections

Revision ID: cf2c93889c9c
Revises: 39bc15ea246e
Create Date: 2025-04-01 23:22:58.103535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf2c93889c9c'
down_revision: Union[str, None] = '39bc15ea246e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bestselling',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_bestselling_id'), 'bestselling', ['id'], unique=False)
    op.create_table('new_arrivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_new_arrivals_id'), 'new_arrivals', ['id'], unique=False)
    op.create_table('on_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_on_sale_id'), 'on_sale', ['id'], unique=False)
    op.create_table('shop_by_need',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('need', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'need', name='_product_need_uc')
    )
    op.create_index(op.f('ix_shop_by_need_id'), 'shop_by_need', ['id'], unique=False)
    op.create_table('trending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_trending_id'), 'trending', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trending_id'), table_name='trending')
    op.drop_table('trending')
    op.drop_index(op.f('ix_shop_by_need_id'), table_name='shop_by_need')
    op.drop_table('shop_by_need')
    op.drop_index(op.f('ix_on_sale_id'), table_name='on_sale')
    op.drop_table('on_sale')
    op.drop_index(op.f('ix_new_arrivals_id'), table_name='new_arrivals')
    op.drop_table('new_arrivals')
    op.drop_index(op.f('ix_bestselling_id'), table_name='bestselling')
    op.drop_table('bestselling')
    # ### end Alembic commands ###
