"""Added User Details model

Revision ID: f778a2dd2c70
Revises: 7afca293261c
Create Date: 2025-02-24 18:40:07.136469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f778a2dd2c70'
down_revision: Union[str, None] = '7afca293261c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerkId', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('pin_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['clerkId'], ['users.clerkId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerkId')
    )
    op.create_index(op.f('ix_user_details_id'), 'user_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_details_id'), table_name='user_details')
    op.drop_table('user_details')
    # ### end Alembic commands ###
